// pages/worker/tasks.jsx
/* eslint-disable react/jsx-key */
import React from "react";
import FilterSearch from "../../src/components/elements/FilterSearch";
import { AppTabs, WorkerLayout, AppTable, Pagination } from "./../../src/";

const tasks = () => {
  return (
    <div className="w-full">
      <AppTabs
        tabHeaders={["bids", "current ", "completed ", "all"]}
        tabItems={[
          <div className=" space-y-4">
            <FilterSearch />
            <AppTable
              tableHeader={[
                "Project",
                "total bids",
                "average bids",
                "my bids",
                "outcome",
              ]}
              tableData={[
                {
                  Project: "bids",
                  "Total Bids": "bids",
                  "Average Bids": "dfas",
                  "My Bids": "dfas",
                  Outcome: "dfas",
                },
                {
                  Project: "two",
                  "Total Bids": "bids",
                  "Average Bids": "dfas",
                  "My Bids": "dfas",
                  Outcome: "dfas",
                },
              ]}
            />
            <Pagination />
          </div>,
          <div className=" space-y-4">
            <FilterSearch />
            <AppTable
              tableHeader={[
                "Project",
                "total bids",
                "average bids",
                "my bids",
                "outcome",
              ]}
              tableData={[
                {
                  Project: "bids",
                  "Total Bids": "bids",
                  "Average Bids": "dfas",
                  "My Bids": "dfas",
                  Outcome: "dfas",
                },
                {
                  Project: "two",
                  "Total Bids": "bids",
                  "Average Bids": "dfas",
                  "My Bids": "dfas",
                  Outcome: "dfas",
                },
              ]}
            />
            <Pagination />
          </div>,
          <div className=" space-y-4">
            <FilterSearch />
            <AppTable
              tableHeader={[
                "Project",
                "total bids",
                "average bids",
                "my bids",
                "outcome",
              ]}
              tableData={[
                {
                  Project: "bids",
                  "Total Bids": "bids",
                  "Average Bids": "dfas",
                  "My Bids": "dfas",
                  Outcome: "dfas",
                },
                {
                  Project: "two",
                  "Total Bids": "bids",
                  "Average Bids": "dfas",
                  "My Bids": "dfas",
                  Outcome: "dfas",
                },
              ]}
            />
            <Pagination />
          </div>,
          <div className=" space-y-4">
            <FilterSearch />
            <AppTable
              tableHeader={[
                "Project",
                "total bids",
                "average bids",
                "my bids",
                "outcome",
              ]}
              tableData={[
                {
                  Project: "bids",
                  "Total Bids": "bids",
                  "Average Bids": "dfas",
                  "My Bids": "dfas",
                  Outcome: "dfas",
                },
                {
                  Project: "two",
                  "Total Bids": "bids",
                  "Average Bids": "dfas",
                  "My Bids": "dfas",
                  Outcome: "dfas",
                },
              ]}
            />
            <Pagination />
          </div>,
        ]}
      />
    </div>
  );
};

export default tasks;
tasks.getLayout = function getLayout(page) {
  return <WorkerLayout>{page}</WorkerLayout>;
};

// resources/js/Pages/User/Tasks.vue
<script setup>
import UserLayout from "./../../Layouts/UserLayout.vue";
import { AppTabs, Card, SortSearch, AppTable, Pagination } from "@/Components";
import { TabPanel } from "@headlessui/vue";
</script>
<template>
    <UserLayout>
        <AppTabs :tabHeaders="['bids', 'current ', 'completed ', 'all']">
            <TabPanel>
                <div class="space-y-4">
                    <SortSearch />
                    <AppTable
                        :tableHeaders="[
                            'bids',
                            'current',
                            'completed',
                            'all',
                            'some',
                        ]"
                        :tableData="[
                            {
                                Project: 'bids',
                                'Total Bids': 'bids',
                                'Average Bids': 'dfas',
                                'My Bids': 'dfas',
                                Outcome: 'dfas',
                            },
                            {
                                Project: 'two',
                                'Total Bids': 'bids',
                                'Average Bids': 'dfas',
                                'My Bids': 'dfas',
                                Outcome: 'dfas',
                            },
                        ]"
                    />
                    <Pagination />
                </div>
            </TabPanel>
            <TabPanel>
                <div class="space-y-4">
                    <SortSearch />
                    <AppTable
                        :tableHeaders="[
                            'bids',
                            'current',
                            'completed',
                            'all',
                            'some',
                        ]"
                        :tableData="[
                            {
                                Project: 'bids',
                                'Total Bids': 'bids',
                                'Average Bids': 'dfas',
                                'My Bids': 'dfas',
                                Outcome: 'dfas',
                            },
                            {
                                Project: 'two',
                                'Total Bids': 'bids',
                                'Average Bids': 'dfas',
                                'My Bids': 'dfas',
                                Outcome: 'dfas',
                            },
                        ]"
                    />
                    <Pagination />
                </div>
            </TabPanel>
            <TabPanel>
                <div class="space-y-4">
                    <SortSearch />
                    <AppTable
                        :tableHeaders="[
                            'bids',
                            'current',
                            'completed',
                            'all',
                            'some',
                        ]"
                        :tableData="[
                            {
                                Project: 'bids',
                                'Total Bids': 'bids',
                                'Average Bids': 'dfas',
                                'My Bids': 'dfas',
                                Outcome: 'dfas',
                            },
                            {
                                Project: 'two',
                                'Total Bids': 'bids',
                                'Average Bids': 'dfas',
                                'My Bids': 'dfas',
                                Outcome: 'dfas',
                            },
                        ]"
                    />
                    <Pagination />
                </div>
            </TabPanel>
            <TabPanel>
                <div class="space-y-4">
                    <SortSearch />
                    <AppTable
                        :tableHeaders="[
                            'bids',
                            'current',
                            'completed',
                            'all',
                            'some',
                        ]"
                        :tableData="[
                            {
                                Project: 'bids',
                                'Total Bids': 'bids',
                                'Average Bids': 'dfas',
                                'My Bids': 'dfas',
                                Outcome: 'dfas',
                            },
                            {
                                Project: 'two',
                                'Total Bids': 'bids',
                                'Average Bids': 'dfas',
                                'My Bids': 'dfas',
                                Outcome: 'dfas',
                            },
                        ]"
                    />
                    <Pagination />
                </div>
            </TabPanel>
        </AppTabs>
    </UserLayout>
</template>
