// resources/js/Components/blocks/Reviews.vue
<script setup>
import SortSearch from "./../elements/SortSearch.vue";
import Pagination from "./../elements/Pagination.vue";
import Review from "./../elements/Review.vue";
</script>

<template>
    <div className="space-y-2">
        <SortSearch />
        <Review />
        <Review />
        <Review />
        <Review />
        <Review />
        <Review />
        <Review />
        <Review />
        <Review />
        <Review />
        <Review />
        <Pagination />
    </div>
</template>

// src/components/blocks/Reviews.jsx
import React from "react";
import FilterSearch from "../elements/FilterSearch";
import Pagination from "../elements/Pagination";

import Review from "../elements/Review";
const Reviews = () => {
  return (
    <div className="space-y-2">
      <FilterSearch />
      <Review />
      <Review />
      <Review />
      <Review />
      <Review />
      <Review />
      <Review />
      <Review />
      <Review />
      <Review />
      <Review />
      <Pagination />
    </div>
  );
};

export default Reviews;
