// Components/elements/Project.jsx
import React from "react";
import Card from "./Card";
import Chip from "./Chip";
import Rating from "./Rating";
import Reviews from "./Reviews";

const Project = () => {
  return (
    <Card>
      <div className="px-3 py-2">
        <div className="flex justify-between">
          <h3 className="text-xl capitalize text-primary font-bold mb-4">
            project title
          </h3>
          <p className="font-bold">2 bids</p>
        </div>

        <p className="mb-2  text-sm font-semibold">
          Budget kes: <span>1500</span> - <span>3000</span>
        </p>

        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repellendus,
          nostrum aliquam. Asperiores corrupti itaque, hic atque repellat
          corporis culpa facilis? Lorem ipsum dolor sit amet consectetur,
          adipisicing elit. Eveniet, magnam!
        </p>
        <div className="space-x-2 mt-4">
          {["html", "css", "js", "react", "node", "mongodb"].map((item) => (
            <Chip key={item} text={item} />
          ))}
        </div>
        <div className="py-4 flex justify-between">
          <div className="flex">
            <Rating rating={3} />
            <Reviews reviews={40} />
          </div>

          <p>18 mins ago</p>
        </div>
      </div>
    </Card>
  );
};

export default Project;

// resources/js/Components/elements/Project.vue
<script setup>
import Card from "./Card.vue";
import { Link } from "@inertiajs/inertia-vue3";
</script>

<template>
    <Card>
        <Link href="/worker/project/id">
            <div className="hover:cursor-pointer">
                <div className="flex justify-between">
                    <h3 className="font-bold text-xl text-primary capitalize">
                        the project name
                    </h3>
                    <div className="flex space-x-4 text-lg ">
                        <p className="font-semibold  text-gray-700">10 bids</p>
                        <div>
                            <p className="font-bold">Kes 700</p>

                            <p className="text-sm">Average bid</p>
                        </div>
                    </div>
                </div>
                <p className="font-semibold mb-2">Budget kes 200 - 400</p>
                <div className="text-sm">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Corporis accusamus placeat nostrum ducimus mollitia
                    consequatur fugiat laboriosam veniam molestias dolore non,
                    excepturi natus, et numquam ut. Debitis optio minima
                    vero?......
                </div>
                <div className="py-2">
                    <ul>
                        <li><Chip item="something" /></li>
                    </ul>
                </div>
                <div className="flex space-x-8">
                    <Rating rating="{1.2}" />
                    <div className="flex items-center space-x-2 text-base">
                        <BsFillChatLeftTextFill className="text-xl" />
                        <span className="-mt-2">10 Reviews</span>
                    </div>
                </div>
            </div>
        </Link>
    </Card>
</template>
